on:
  workflow_dispatch:
name: Issue and PR hygiene
jobs:
  stale:
    uses: krakendio/.github/.github/workflows/stale.yml@main
  lock-threads:
    uses: krakendio/.github/.github/workflows/lock-threads.yml@main
